version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sqltrace_dev
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/01_init_db.sql
      - ./scripts/sample_data.sql:/docker-entrypoint-initdb.d/02_sample_data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MySQL database for multi-engine testing
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: sqltrace_dev
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init_mysql.sql:/docker-entrypoint-initdb.d/01_init_mysql.sql
      - ./scripts/sample_data_mysql.sql:/docker-entrypoint-initdb.d/02_sample_data_mysql.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "mysql", "-pmysql"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: --default-authentication-plugin=mysql_native_password

  # SQLite is file-based, but we can use a container for testing
  sqlite:
    image: alpine:latest
    volumes:
      - sqlite_data:/data
      - ./scripts/init_sqlite.sql:/scripts/init_sqlite.sql
      - ./scripts/sample_data_sqlite.sql:/scripts/sample_data_sqlite.sql
    command: |
      sh -c "
        apk add --no-cache sqlite &&
        sqlite3 /data/sqltrace_dev.db < /scripts/init_sqlite.sql &&
        sqlite3 /data/sqltrace_dev.db < /scripts/sample_data_sqlite.sql &&
        tail -f /dev/null
      "
    healthcheck:
      test: ["CMD", "test", "-f", "/data/sqltrace_dev.db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:7
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sqltrace.dev
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8080:80"
    depends_on:
      - postgres
    profiles:
      - admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  mysql_data:
  sqlite_data:
  pgadmin_data:
